import {Component} from 'react'

class Philosophie extends Component{
    render(){
        return(
            <>
                <h1>Philosophie</h1>
                <p>Der USC Bayreuth will Studierenden die Möglichkeit geben, auf einem für sie unkomplizierten Weg weiter Verbandssport zu betreiben. Viele Studierende sind zugezogen und können beim USC eine neue, sportliche Heimat finden. Da der Verein von Studierenden für Studierende ist, kennen wir die typischen Herausforderungen im Studium.</p>
                <p>Du hast eine schwierige Klausur und musst lernen? Zuhause findet eine große Familienfeier statt? Beim USC ist das kein Problem, denn das kommt bei jedem von uns vor. Viele Vereine fordern von ihren Spielern bei jedem Training und Spiel anwesend zu sein. Wir verstehen, wenn ihr mal nicht da seid. Das soll aber keinesfalls bedeuten, dass das Sportliche bei uns nicht wichtig ist. Wir sind trotz hoher Fluktuation der Sporttreibenden bestrebt in jedem Spiel, Turnier oder Training Höchstleistung zu bringen und Erfolge davon zu tragen. Angesichts der Vergangenheit ist uns dies bisher auch gelungen.</p>
                <p>Neben dem Sportlichen findest du bei uns auch die Möglichkeit, beruflich erste Erfahrungen zu sammeln und dir ein lebenslanges Netzwerk aufzubauen.</p>
                <p>Du willst ein Praktikum machen? Wir ermöglichen dir deine ersten praktischen Erfahrungen. Über unsere Partnerunternehmen sind bereits Kontakte und Ausschreibungen für Stellen vorhanden. Lokal ansässige Unternehmen können somit unkompliziert Kontakte zu den an der Universität vorhandenen Talenten knüpfen. Wir wollen unsere Mitglieder, zukünftige Ingenieure, Ökonomen, Juristen und natürlich auch Absolventen/innen aller anderen Fachrichtungen, über das Studium hinaus in der Region halten. Das Potential der Universität kann somit das Abwandern von Unternehmen verringern, bzw. die Neuansiedelung von Unternehmen unterstützen. Dadurch wird die Region langfristig gestärkt.</p>
                <p>Zudem gibt es die Möglichkeit über unsere Alumni in Kontakt mit den verschiedensten Unternehmen zu kommen, die ein erster Kickstart in Deinem beruflichen Werdegang sein können.</p>
                <p>Ein kontinuierlicher Spielbetrieb während Vorlesungszeit und Semesterferien ermöglicht eine schnelle Integration in Bayreuth. Bei uns findest Du nicht nur Sportkameraden, sondern auch neue Freunde für die Zeit des Studiums oder fürs Leben. Unsere jungen Mitglieder sehen Bayreuth dadurch nicht mehr nur als kurzen Abschnitt ihrer akademischen Bildung, sondern werden hier verwurzelt.</p>
                <p>Beim USC selbst entwickelt sich jedes Mitglied weiter, sportlich sowie persönlich. Disziplin, Respekt füreinander und gegenseitige Unterstützung bilden die Basis unseres Vereins, des Amateursports, aber auch des grundsätzlichen gesellschaftlichen Miteinander. Wir stehen füreinander ein und verfolgen unsere Ziele gemeinsam. Unsere Werte Offenheit, Toleranz familiäre Atmosphäre und Leidenschaft leben wir in vollen Zügen aus!</p>
                <p>Da der USC Bayreuth der erste von Studierenden gegründete und rein studentisch organisierte Sportverein in Bayern ist, müssen selbst Vorstandsposten oder Abteilungsleitungen von sehr jungen Persönlichkeiten besetzt werden. Beim USC kann jeder in einem freundschaftlichen Verhältnis einfach nur Sport treiben oder auch Verantwortung übernehmen und zur Entwicklung des Vereins beitragen. In verschiedenen „Squads“ werden die Social Media Präsenz, die Arbeit mit Sponsoren, das Planen von Events oder das wöchentlich Spiel- und Trainingsgeschehen selbst besprochen und verwaltet. Bei uns ist also wirklich für jeden was dabei.</p>
                <p>Wurde dein Interesse geweckt? Dann melde dich bei uns entweder per Mail an <a className='mail-to' href='mailto:info@usc-bayreuth.de'>info@usc-bayreuth.de</a> oder über unsere Social-Media-Kanäle (<a className='link' href='https://www.facebook.com/uscbayreuth/' target="_blank" rel="noreferrer">Facebook</a>, <a className='link' href='https://www.instagram.com/usc_bayreuth/' target="_blank" rel="noreferrer">Instagram</a>).</p>
            </>
        )
    }
}

export default Philosophie